import streamlit as st

st.set_page_config(page_title="Selector App", layout="centered")

st.title("Select Brands, Categories, Statuses, and Stores")

brands = [
    "Bella Canvas",
    "District",
    "Flexfit",
    "Gildan",
    "Mercer Mettle",
    "Nike",
    "Port Company",
    "Port Authority",
    "Richardson",
]

product_categories = [
    "Sweatshirts Fleece 1/2 1/4 Zip",
    "T-Shirts 100% Cotton",
    "Outerwear 3 in 1",
    "T-Shirts 5.5 6 100% Cotton",
    "T-Shirts 50/50 Blend",
    "T-Shirts 6.6 1 100% Cotton",
    "Ladies Activewear",
    "Workwear Aprons",
    "Activewear Athletic Warm-ups",
    "Outerwear Athletic Warm-ups",
    "Bags Backpacks",
    "Polos Knits Basic Knits",
    "Activewear Basketball",
    "Accessories Blankets",
    "Ladies Bottoms",
    "Bags Briefcases Messengers",
    "Caps Camouflage",
    "Outerwear Camouflage",
    "Caps Canvas",
    "Youth Caps",
    "Juniors Young Men Caps",
    "Bags Coolers Lunch Bags",
    "Outerwear Corporate Jackets",
    "Polos Knits Cotton",
    "Woven Shirts Cotton Poly Blend",
    "Sweatshirts Fleece Crewnecks",
    "Polos Knits Easy Care",
    "Woven Shirts Easy Care",
    "Caps Fashion",
    "T-Shirts Fashion",
    "Ladies Fashion",
    "Polos Knits Fashion",
    "Caps Fitted",
    "Sweatshirts Fleece Fleece",
    "Caps Fleece Beanies",
    "Caps Flexfit",
    "Caps Full Brim",
    "Sweatshirts Fleece Full Zip",
    "Outerwear Golf Outerwear",
    "Headwear",
    "Sweatshirts Fleece Heavyweight",
    "Sweatshirts Fleece Hoodie",
    "Workwear Industrial Work Shirts",
    "Youth Infant Toddler",
    "Outerwear Insulated Jackets",
    "Juniors Young Men",
    "Ladies",
    "Polos Knits Ladies",
    "Outerwear Ladies",
    "Woven Shirts Ladies",
    "Activewear Ladies",
    "T-Shirts Ladies",
    "Sweatshirts Fleece Ladies",
    "T-Shirts Long Sleeve",
    "Workwear Medical Scrubs",
    "Personal Protection Medical Scrubs",
    "Caps Mesh Back",
    "Accessories Other",
    "Ladies Outerwear",
    "Woven Shirts Oxfords",
    "Activewear Pants Shorts",
    "Outerwear Parkas Shells Systems",
    "Polos Knits Performance",
    "Sweatshirts Fleece Performance",
    "T-Shirts Performance",
    "Activewear Performance",
    "Caps Performance Athletic",
    "Personal Protection",
    "Caps Pigment Garment Dyed",
    "Workwear Polos",
    "Ladies Polos Knits",
    "Tall Polos Knits",
    "Outerwear Polyester Fleece",
    "Outerwear Rainwear",
    "T-Shirts Ring Spun",
    "Workwear Safety",
    "Caps Safety",
    "Personal Protection Safety",
    "Polos Knits Silk Touch",
    "Outerwear Soft Shells",
    "T-Shirts Specialty",
    "Bags Specialty Bags",
    "Workwear Stain Soil Resistant",
    "Caps Stretch to Fit",
    "Polos Knits Sweaters",
    "Sweatshirts Fleece Sweatpants",
    "Youth Sweatshirts Fleece",
    "Ladies Sweatshirts Fleece",
    "Tall Sweatshirts Fleece",
    "T-Shirts",
    "Ladies T-Shirts",
    "Youth T-Shirts",
    "Tall T-Shirts",
    "Workwear T-Shirts",
    "Tall",
    "Polos Knits Tall",
    "T-Shirts Tall",
    "Sweatshirts Fleece Tall",
    "T-Shirts Tanks",
    "Activewear Tanks",
    "Infant Toddler Tops Bottoms",
    "Bags Travel Bags",
    "Caps Twill",
    "Workwear Work Jackets",
    "Outerwear Work Jackets",
    "Polos Knits Workwear",
    "Woven Shirts Workwear",
    "T-Shirts Workwear",
    "Woven Shirts",
    "Ladies Woven Shirts",
    "T-Shirts Youth",
    "Sweatshirts Fleece Youth",
    "Caps Youth",
    "Accessories",
    "Activewear",
    "Bags",
    "Caps",
    "Casual T-Shirts",
    "Ladies Womens",
    "Outerwear",
    "Polos Knits",
    "Sweatshirts Fleece",
    "Workwear",
    "Woven Dress Shirts",
    "Youth",
]

order_statuses = [
    "Ready for Hot Press",
    "Ready to Print",
    "Ready to Sew Embroidery",
    "Needs Artwork",
    "Needs Mockup",
    "Needs Proof",
    "Needs Sewout",
    "Waiting on Art Approval",
    "New Order",
    "Quote",
    "Art Approved",
    "Out of House Processing",
    "Billing Review",
    "Payment Request",
    "Shipped Ready for Pickup",
    "325618",
    "Paid Order Closed",
    "Store Order",
]

stores = [
    "Alchemy Spring 2026 Store",
    "Alchemy Sound and Vision",
    "Amvan Employee Store",
    "Store Test",
    "C E G C",
    "City of North Mankato Shirt Order",
    "Contents Store",
    "Danbarnettstore",
    "Delta Phi Omega Gac",
    "Dsa Car Sales",
    "Eaa 1658",
    "Mankato East Football as One 2026",
    "Flex Fitness",
    "Gigli Merch",
    "Gigli Bartender Shirts",
    "Goodrich Construction24",
    "Gray Duck Crossfit Winter",
    "Heyn Brothers Spring Store 2026",
    "Heyn Brothers Convenience Store July 2026 Minimum",
    "Kato Mtb",
    "Lakes Diesel Fall Store 25",
    "Lakesdiesel",
    "Last Man Standing Fall 2024",
    "Lastmanstanding",
    "Levelone Eps4444",
    "Marshall Building Remodeling",
    "Marshall Build Cals Metals Dec24",
    "Mca Grrls 2025",
    "Mgm Dec 24 Store",
    "Mgm Mankato Apparel",
    "Mn Dnr Parks Trails",
    "Mpls 81",
    "Nielsen Employee Store Spring 2026",
    "Nielsen Blacktopping Safety",
    "Olympic Fire",
    "Prairie Cottages Apparel Store",
    "Little Star Learning Center",
    "Rice",
    "Rounders Sports Bar Staff",
    "Rounders Employee Store 2026",
    "Roundersstaffstore",
    "Rucker Lawn Care",
    "Soho",
    "Soho Employee Store 2026",
    "Soho Employee Store",
    "Srp Fall 2025 Store",
    "Srp",
    "St Peter Pickleball Store 25",
    "Support 81 Mlps",
    "Tailwind Group",
    "Techgritteststore2",
    "Techgrit Testing",
    "Techgritcustoms",
    "Test Store 7",
    "Tg Special Moments",
    "Tgteststore6",
    "Trek Supply Store",
    "Trek Supply Spring Summer 2025",
    "Nielsen Employee Store",
    "United Surface Preparation",
    "V Tek Summer 2026 Store",
    "West Hennepin Police Fall Store",
    "Za Pizza",
]

selected_brands = st.multiselect("Brands", brands)
selected_categories = st.multiselect("Product Categories", product_categories)
selected_statuses = st.multiselect("Order Statuses", order_statuses)
selected_stores = st.multiselect("Stores", stores)

st.subheader("Selected Brands")
if selected_brands:
    for brand in selected_brands:
        st.write(f"- {brand}")
else:
    st.caption("No brands selected.")

st.subheader("Selected Categories")
if selected_categories:
    for category in selected_categories:
        st.write(f"- {category}")
else:
    st.caption("No categories selected.")

st.subheader("Selected Order Statuses")
if selected_statuses:
    for status in selected_statuses:
        st.write(f"- {status}")
else:
    st.caption("No order statuses selected.")

st.subheader("Selected Stores")
if selected_stores:
    for store in selected_stores:
        st.write(f"- {store}")
else:
    st.caption("No stores selected.")
